# Evaluate Metrics of Regressor Models

The list of Metrics to evaluate are:


**Group 1 R2**
- R2

**Group 2 MSE**
- MSE

**Group 3 RMSE**
- RMSE
- RMSE MEAN RATIO
- RMSE IQR RATIO

**Group 4 MAE**
- MAE
- MAE MEAN RATIO
- MAE IQR RATIO

In [1]:
import os
# fix root path to save outputs
actual_path = os.path.abspath(os.getcwd())
list_root_path = actual_path.split('\\')[:-1]
root_path = '\\'.join(list_root_path)
os.chdir(root_path)
print('root path: ', root_path)

root path:  D:\github-mi-repo\Offline-Evaluation-ML-Regression

# RUN

In [67]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt


# metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from scipy.stats import iqr

### 1. Load data

In [3]:
### DEFINE LIST FEARTURES - TARGET (order data to have the same order in the features always)
list_features = ['AveOccup', 'Latitude', 'Population', 'AveBedrms', 'HouseAge', 'Longitude', 'AveRooms', 'MedInc']
target = 'Price'

In [4]:
### LOAD DATA
X_train = pd.read_pickle('artifacts/data/X_train.pkl')
X_test = pd.read_pickle('artifacts/data/X_test.pkl')
y_train = pd.read_pickle('artifacts/data/y_train.pkl')
y_test = pd.read_pickle('artifacts/data/y_test.pkl')

In [5]:
print('shape data')
print('\n\n TRAIN')
print('X_train: ', X_train.shape)
print('y_train: ', y_train.shape)

print('\n\n TEST')
print('X_test: ', X_test.shape)
print('y_test: ', y_test.shape)

shape data


 TRAIN
X_train:  (14540, 8)
y_train:  (14540, 1)


 TEST
X_test:  (3636, 8)
y_test:  (3636, 1)

### 2. Load Models
Load all the models in a dictory

In [6]:
## define list of models - list to have always the same order.
#### In this example, the strings in the list are the same with the models were saved
list_models_names = [
    "lr",
    
    "tree_simple",
    "tree_default",
    
    "rf_simple",
    "rf_default",

    "gb_simple",
    "gb_default",

    "xgb_simple",
    "xgb_default",

    "mlp_simple",
    "mlp_default"
]

In [7]:
# define path to folder models
path_folder_models = 'artifacts/models/'

In [9]:
### load models
dict_models = {}
for model_name in list_models_names:
    print(f'loading model: {model_name}')
    path_model = path_folder_models + f'{model_name}.pkl'
    with open(path_model, 'rb') as artifact:
        dict_models[model_name] = pickle.load(artifact)

loading model: lr
loading model: tree_simple
loading model: tree_default
loading model: rf_simple
loading model: rf_default
loading model: gb_simple
loading model: gb_default
loading model: xgb_simple
loading model: xgb_default
loading model: mlp_simple
loading model: mlp_default

### 3. Define Functions to calculate metrics

In [19]:
# show version scikit-learn - since version 1.4 some codes to evaluate metrics changed
!pip show scikit-learn

Name: scikit-learn
Version: 1.3.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author:
Author-email:
License: new BSD
Location: d:\anaconda\envs\data-science-python-3-10-explanaible-ai\lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: alibi, category-encoders, eli5, lime, mlflow, PDPbox, shap, shapash, skope-rules

In [95]:
def calculate_metrics_regressors_models(y, y_pred, model_name, decimals_round = None):
    """
    Calculate a certain number of metrics to evaluate regression models. The metrics are rounded to X decimals

    Args
        y (dataframe): y true
        y_pred (dataframe): y predicted with the model. In this codes are passed y_pred instead of X
        model_name (string): name of the model. This name is used when the metrics are saved to identify the model of these metrics
        decimals_round = Number of decimals to round the values. Defult None, no round the values.

    Return
        metrics_regressors (dataframe): dataframe with the metrics of the model in this datasets. Row: name metrics. Columns: value metrics
    """

    #### R2
    r2 = r2_score(y, y_pred)
    
    #### MSE
    mse = mean_squared_error(y, y_pred, squared = True)
    
    #### RMSE
    rmse = mean_squared_error(y, y_pred, squared = False)
    
    #### RMSE_MEAN_RATIO
    # rmse mean ratio: rmse / mean_y_true
    rmse_mean_ratio = rmse / y.mean().values[0]
    
    #### RMSE_IQR_RATIO
    # rmse iqr ratio: rmse / iqr_y_true
    rmse_iqr_ratio = rmse / iqr(y)
    
    #### MAE
    mae = mean_absolute_error(y, y_pred)
    
    #### MAE_RATIO
    mae_mean_ratio = mae / y.mean().values[0]
    
    #### MAE_IQR_RATIO
    mae_iqr_ratio = mae / iqr(y)
    
    
    
    #### JOIN INTO ONE DATAFRAME
    # create dataframe
    metrics_regressors = pd.DataFrame(columns = [model_name])
    
    # add metrics
    metrics_regressors.loc['r2', model_name] = r2
    metrics_regressors.loc['mse', model_name] = mse
    metrics_regressors.loc['rmse', model_name] = rmse
    metrics_regressors.loc['rmse_mean_ratio', model_name] = rmse_mean_ratio
    metrics_regressors.loc['rmse_iqr_ratio', model_name] = rmse_iqr_ratio
    metrics_regressors.loc['mae', model_name] = mae
    metrics_regressors.loc['mae_mean_ratio', model_name] = mae_mean_ratio
    metrics_regressors.loc['mae_iqr_ratio', model_name] = mae_iqr_ratio
    
    # round
    metrics_regressors = metrics_regressors.astype('float')
    if decimals_round:
        metrics_regressors = metrics_regressors.round(decimals_round)


    return metrics_regressors

In [121]:
metrics_regressors = pd.DataFrame(index = [model_name])
metrics_regressors['r2'] = r2
metrics_regressors

                   r2
mlp_default  0.681128

In [96]:
# show examples
calculate_metrics_regressors_models(y = y_train,
                                    y_pred = dict_models['lr'].predict(X_train),
                                    model_name = 'lr',
                                    decimals_round = 3
                                   )

                    lr
r2               0.681
mse              0.398
rmse             0.631
rmse_mean_ratio  0.300
rmse_iqr_ratio   0.443
mae              0.471
mae_mean_ratio   0.224
mae_iqr_ratio    0.331

### 4. Calculate metrics train

In [98]:
### calculate metrics for all models, TRAIN DATA
metrics_train = pd.DataFrame()
for m_name in list_models_names:
    print(f'calculating metrics: {m_name}')

    # calcualte metrics
    y_pred_train = dict_models[m_name].predict(X_train)
    metrics_aux = calculate_metrics_regressors_models(y = y_train,
                                                      y_pred = y_pred_train,
                                                      model_name = m_name,
                                                      decimals_round = 3
                                                     )

    # append ouput dataframe
    metrics_train = pd.concat([metrics_train, metrics_aux], axis = 1)

calculating metrics: lr
calculating metrics: tree_simple
calculating metrics: tree_default
calculating metrics: rf_simple
calculating metrics: rf_default
calculating metrics: gb_simple
calculating metrics: gb_default
calculating metrics: xgb_simple
calculating metrics: xgb_default
calculating metrics: mlp_simple
calculating metrics: mlp_default

In [99]:
metrics_train

,lr,tree_simple,tree_default,rf_simple,rf_default,gb_simple,gb_default,xgb_simple,xgb_default,mlp_simple,mlp_default
r2,0.681,0.497,1.0,0.457,0.974,0.234,0.816,0.639,0.950,-0.000,0.627
mse,0.398,0.628,0.0,0.678,0.032,0.957,0.230,0.450,0.063,1.249,0.466
rmse,0.631,0.793,0.0,0.824,0.179,0.978,0.480,0.671,0.251,1.118,0.683
rmse_mean_ratio,0.300,0.377,0.0,0.392,0.085,0.465,0.228,0.319,0.119,0.531,0.325
rmse_iqr_ratio,0.443,0.556,0.0,0.578,0.126,0.686,0.337,0.471,0.176,0.784,0.479
mae,0.471,0.601,0.0,0.624,0.118,0.766,0.341,0.516,0.179,0.885,0.508
mae_mean_ratio,0.224,0.286,0.0,0.297,0.056,0.364,0.162,0.245,0.085,0.421,0.242
mae_iqr_ratio,0.331,0.421,0.0,0.438,0.082,0.537,0.239,0.362,0.125,0.621,0.356

### 5. Calculate metrics test

In [100]:
### calculate metrics for all models, TEST DATA
metrics_test = pd.DataFrame()
for m_name in list_models_names:
    print(f'calculating metrics: {m_name}')

    # calcualte metrics
    y_pred_test = dict_models[m_name].predict(X_test)
    metrics_aux = calculate_metrics_regressors_models(y = y_test,
                                                      y_pred = y_pred_test,
                                                      model_name = m_name,
                                                      decimals_round = 3
                                                     )

    # append ouput dataframe
    metrics_test = pd.concat([metrics_test, metrics_aux], axis = 1)

calculating metrics: lr
calculating metrics: tree_simple
calculating metrics: tree_default
calculating metrics: rf_simple
calculating metrics: rf_default
calculating metrics: gb_simple
calculating metrics: gb_default
calculating metrics: xgb_simple
calculating metrics: xgb_default
calculating metrics: mlp_simple
calculating metrics: mlp_default

In [101]:
metrics_test

,lr,tree_simple,tree_default,rf_simple,rf_default,gb_simple,gb_default,xgb_simple,xgb_default,mlp_simple,mlp_default
r2,0.681,0.484,0.630,0.434,0.810,0.232,0.791,0.615,0.837,-0.000,0.611
mse,0.391,0.634,0.455,0.695,0.233,0.944,0.257,0.473,0.200,1.228,0.478
rmse,0.626,0.796,0.674,0.834,0.483,0.971,0.507,0.688,0.447,1.108,0.691
rmse_mean_ratio,0.300,0.382,0.324,0.400,0.232,0.466,0.243,0.330,0.214,0.532,0.332
rmse_iqr_ratio,0.464,0.591,0.501,0.619,0.359,0.721,0.376,0.511,0.332,0.823,0.513
mae,0.465,0.604,0.433,0.632,0.315,0.760,0.353,0.524,0.295,0.875,0.511
mae_mean_ratio,0.223,0.290,0.208,0.303,0.151,0.365,0.169,0.251,0.142,0.420,0.245
mae_iqr_ratio,0.345,0.448,0.321,0.469,0.234,0.564,0.262,0.389,0.219,0.649,0.379

### 6. Save Metrics
Save metrics in a excel

In [102]:
metrics_train.to_excel('metrics_train_basic_models.xlsx')

In [107]:
metrics_train[['lr']].max()

lr    0.681
dtype: float64

In [113]:
metrics_train.T

,r2,mse,rmse,rmse_mean_ratio,rmse_iqr_ratio,mae,mae_mean_ratio,mae_iqr_ratio
lr,0.681,0.398,0.631,0.300,0.443,0.471,0.224,0.331
tree_simple,0.497,0.628,0.793,0.377,0.556,0.601,0.286,0.421
tree_default,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
rf_simple,0.457,0.678,0.824,0.392,0.578,0.624,0.297,0.438
rf_default,0.974,0.032,0.179,0.085,0.126,0.118,0.056,0.082
gb_simple,0.234,0.957,0.978,0.465,0.686,0.766,0.364,0.537
gb_default,0.816,0.230,0.480,0.228,0.337,0.341,0.162,0.239
xgb_simple,0.639,0.450,0.671,0.319,0.471,0.516,0.245,0.362
xgb_default,0.950,0.063,0.251,0.119,0.176,0.179,0.085,0.125
mlp_simple,-0.000,1.249,1.118,0.531,0.784,0.885,0.421,0.621
mlp_default,0.627,0.466,0.683,0.325,0.479,0.508,0.242,0.356

In [110]:
metrics_train.T[['r2']].max()

r2    1.0
dtype: float64

In [112]:
metrics_train.T[['r2']].idxmax()

r2    tree_default
dtype: object